version: '3.8'

services:
  db:
    image: mysql:8.0 
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: webapp_db 
      MYSQL_USER: webapp_user 
      MYSQL_PASSWORD: password 
    ports:
      - "3306"
    volumes:
      - sql:/var/lib/mysql 
      - ./db-schema.sql:/docker-entrypoint-initdb.d/db-script.sql

  webapp:
    image: webapp:1.0.3
    container_name: tomcat_server
    ports:
      - "80:8080" 
    depends_on:
      - db 
    environment:
      DB_HOST: db 
      DB_NAME: webapp_db
      DB_USER: webapp_user
      DB_PASSWORD: password
      DB_PORT: 3306

volumes:
  sql:
