def gv

pipeline {
    agent any
    stages {
        stage("init") {
            steps {
                script {
                    dir('java-webapp') {
                        gv = load "script.groovy"
                    }
                }
            }
        }
        stage("build War file") {
            steps {
                script {
                    dir('java-webapp') {
                        gv.buildWar()
                    }
                }
            }
        }
        stage("build image") {
            steps {
                script {
                    dir('java-webapp') {
                        gv.buildImage()
                    }
                }
            }
        }
        stage("deploy") {
            steps {
                script {
                    dir('java-webapp') {
                         gv.deployApp()
                    }
                }
            }
        }
    }   
}
